### ISSUE TITLE
make a contact us page

### ISSUE THREAD

**Issue by ADITYARAGHAV2001** [ADITYARAGHAV2001/Gym-Website#5]

**Comment by tejus0** [comment]
hey @ADITYARAGHAV2001 i want to make contact page of your website . So assign me this issue under hacktoberfest

**Comment by tejus0** [comment]
Hey @ADITYARAGHAV2001 please mark it as hacktoberfest otherwise it will not be counted down in my progress.

**Comment by ADITYARAGHAV2001** [comment]
done

**Comment by tejus0** [comment]
hey @ADITYARAGHAV2001 please check i made the PR .

**Comment by tejus0** [comment]
@ADITYARAGHAV2001 as the page is built so can you close this issue?
